#!/usr/bin/env python3
"""gen_batch.py — generate the host stub-surface fuzz batch. Scans every
TARGET_NATIVE unit for void(void) function bodies (callable with no args, so no
arg-deref crash masks the engine call) and emits a batch program that runs each
in a forked, stderr-captured, alarm-guarded child against the seeded arena.

Per function it reports clean / [STUB]->name (the reaching caller + the missing
shim, for the decomper) / [CRASH] / [TIMEOUT]. Output: a self-contained .c.

Usage: gen_batch.py <src_root> > batch_gen.c
"""
import re, sys, glob, os

src_root = sys.argv[1]
funcs = []
for f in sorted(glob.glob(os.path.join(src_root, "usa/text/*.c"))):
    s = open(f).read()
    if "TARGET_NATIVE" not in s:        # only units actually in the native link
        continue
    for m in re.finditer(r'^void ([A-Za-z_][A-Za-z0-9_]*)\(void\)\s*\{', s, re.M):
        funcs.append(m.group(1))
funcs = sorted(set(funcs))

W = sys.stdout.write
W('/* GENERATED by gen_batch.py — host stub-surface fuzz batch. */\n')
W('#include <stdio.h>\n#include <stdlib.h>\n#include <string.h>\n#include <unistd.h>\n#include <sys/wait.h>\n')
W('extern unsigned char g_dataArena[];\n')
W('#define ARENA_BASE 0x138180u\n')

# Seed dir: default the committed front-end seed (state/); override via SEED_DIR
# (e.g. "tools/ee/eetest/state/inlevel_active") to fuzz against a live in-level
# capture. Mirrors the SEED_DIR override in run_state_suite.sh / auto_validate.sh.
seed_dir = os.environ.get("SEED_DIR", "tools/ee/eetest/state")
for fn in funcs:
    W('extern void %s(void);\n' % fn)
W('typedef struct { const char *name; void (*fn)(void); } Target;\n')
W('static Target targets[] = {\n')
for fn in funcs:
    W('  { "%s", %s },\n' % (fn, fn))
W('};\n')
W('#define NTARGETS (int)(sizeof(targets)/sizeof(targets[0]))\n')
W(r'''
static void seed(const char *p, unsigned rom, unsigned n) {
    FILE *f = fopen(p, "rb");
    if (f) { (void)!fread(g_dataArena + (rom - ARENA_BASE), 1, n, f); fclose(f); }
}
static int n_clean, n_stub, n_crash, n_timeout;
static void run_one(const char *name, void (*fn)(void)) {
    int pp[2]; if (pipe(pp)) return;
    pid_t pid = fork();
    if (pid == 0) {
        dup2(pp[1], 2); close(pp[0]); close(pp[1]);
        alarm(3);                 /* hang-guard: SIGALRM if it loops */
        fn();
        _exit(0);
    }
    close(pp[1]);
    char buf[256]; int got = (int)read(pp[0], buf, sizeof(buf) - 1);
    if (got < 0) got = 0; buf[got] = 0; close(pp[0]);
    int st; waitpid(pid, &st, 0);
    if (WIFEXITED(st)) {
        int e = WEXITSTATUS(st);
        if (e == 0) { n_clean++; }
        else if (e == 99) {
            char stub[128] = "?"; char *s = strstr(buf, "NATIVE STUB HIT: ");
            if (s) sscanf(s + 17, "%127[^ \n]", stub);
            printf("  [STUB ] %-18s -> %s\n", name, stub); n_stub++;
        } else { printf("  [exit%d] %-18s\n", e, name); }
    } else if (WIFSIGNALED(st)) {
        int sig = WTERMSIG(st);
        if (sig == 14) { printf("  [TIMEOUT] %-16s (loops on seeded state)\n", name); n_timeout++; }
        else { printf("  [CRASH] %-18s sig %d\n", name, sig); n_crash++; }
    }
}
int main(void) {
    setvbuf(stdout, 0, _IONBF, 0);   /* unbuffered: stub-children's exit() must not re-flush a shared buffer */
''')
# seed() calls emitted separately so the raw printf-format literals above aren't
# mangled by the seed_dir interpolation. Regions are read from the active seed's
# snapshot.json (not hardcoded) so the host sweep seeds EXACTLY what was captured
# — auto-covering a widened globals window, the in-level relocated band, the
# dynamic deref-object address (e.g. sky_obj), and any extra heap regions. Only
# regions wholly inside the arena block [ARENA_BASE, ARENA_BASE+0x146780) can be
# placed; any outside (a far heap object) is skipped with a note. Falls back to
# the canonical front-end windows if the seed has no snapshot.json yet.
import json
ARENA_TOP = 0x138180 + 0x146780
snap = os.path.join(seed_dir, "snapshot.json")
if os.path.exists(snap):
    regions = [(r["name"], r["addr"], r["len"]) for r in json.load(open(snap)).get("regions", [])]
else:
    regions = [("globals", 0x1A7000, 0x15000), ("input", 0x138300, 0x400),
               ("sound", 0x189E00, 0x4000), ("sky_obj", 0x1F4000, 0x8000)]
    sys.stderr.write("gen_batch: no %s — using fallback windows\n" % snap)
for name, addr, length in regions:
    if 0x138180 <= addr and addr + length <= ARENA_TOP:
        W('    seed("%s/%s.bin", 0x%X, 0x%X);\n' % (seed_dir, name, addr, length))
    else:
        W('    /* skip %s @0x%X+0x%X — outside arena block, not placeable */\n' % (name, addr, length))
        sys.stderr.write("gen_batch: region %s @0x%X+0x%X outside arena — skipped\n" % (name, addr, length))
W(r'''    printf("== host stub-surface fuzz: %d void(void) TARGET_NATIVE funcs vs New Game ==\n", NTARGETS);
    fflush(stdout);
    for (int i = 0; i < NTARGETS; i++) run_one(targets[i].name, targets[i].fn);
    printf("== summary: %d clean, %d STUB, %d crash, %d timeout (of %d) ==\n",
           n_clean, n_stub, n_crash, n_timeout, NTARGETS);
    return 0;
}
''')
sys.stderr.write("gen_batch: %d void(void) targets\n" % len(funcs))
