#!/usr/bin/env bash
# progress.sh — autogenerated decomp/match/coverage readout for the Going
# Commando tree. FAST STATIC MODE only (default): pure grep/parse over the
# working tree — no VM, no docker, no build. Instant.
#
#   tools/ee/progress.sh            # static estimate, both regions
#   tools/ee/progress.sh --verify   # (stub) objdiff-verified byte-exact mode
#   PROGRESS_ROOT=/path/to/tree tools/ee/progress.sh   # run against another
#                                   # checkout (e.g. a master worktree)
#
# DEFINITIONS (STATIC ESTIMATE — read the caveat in the output):
#   carved fn   = one per-function nonmatching .s under
#                 going-decompiled/asm/<region>/nonmatchings/<seg>/<unit>/<fn>.s
#                 (splat emits one per split function regardless of match
#                 status — this is the denominator).
#   matched-by-C= carved fn whose unit HAS a src/<region>/<seg>/<unit>.c and
#                 whose name appears in NO INCLUDE_ASM() anywhere in that
#                 region's src tree (the INCLUDE_ASM was removed → a real C
#                 definition stands in for it). NOT objdiff-verified.
#   coverage    = fn still INCLUDE_ASM'd, but the INCLUDE_ASM sits inside an
#                 `#ifndef TARGET_NATIVE` guard (a portable #else body exists).
#   bare wall   = fn still INCLUDE_ASM'd with no #ifndef TARGET_NATIVE guard.
#   asm-only    = fn whose unit has no .c at all yet (disassembled, uncarved).
#   matched + coverage + walls + asm-only == carved total, exactly.
#
# Guard detection is a line-oriented heuristic: an INCLUDE_ASM line seen after
# `#ifndef TARGET_NATIVE` and before the next `#else`/`#endif` counts as
# guarded. That is the tree's single uniform pattern today; if a new guard
# spelling appears (#if !defined...), extend GUARD_RE below.
set -u
ROOT="${PROGRESS_ROOT:-$(cd "$(dirname "$0")/../.." && pwd)}"
GD="$ROOT/going-decompiled"
GREP="command grep"
FIND="command find"

if [ "${1:-}" = "--verify" ]; then
  echo "TODO: objdiff-verified mode is NOT implemented."
  echo "Plan: for each region+unit run tools/ee/objdiff_build.sh (VM, slow),"
  echo "then tools/ee/verify_match_uu.sh per non-INCLUDE_ASM fn to count TRUE"
  echo "byte-exact matches (words+relocs — never objdiff fuzzy%). Until then,"
  echo "byte-exact truth per fn comes from the tester's #44 raw gate."
  exit 2
fi

if [ ! -d "$GD" ]; then
  echo "progress.sh: $GD not found (set PROGRESS_ROOT?)" >&2
  exit 1
fi

echo "=== Going Commando decomp progress — STATIC ESTIMATE ($(date +%F)) ==="
echo "tree: $ROOT"
echo "CAVEAT: 'matched-by-C' means the INCLUDE_ASM was removed and real C"
echo "stands in its place. It is NOT an objdiff-verified byte-exact claim —"
echo "byte-exact status is gated per-fn by the tester (raw words+relocs)."
echo

TMP="$(mktemp -d /tmp/gcprogress.XXXXXX)" || exit 1
trap 'rm -rf "$TMP"' EXIT

tot_all=0; mat_all=0; cov_all=0; wall_all=0; only_all=0

for region in usa eu; do
  NM="$GD/asm/$region/nonmatchings"
  SRC="$GD/src/$region"
  [ -d "$NM" ] || { echo "region $region: no nonmatchings dir, skipped"; continue; }

  # 1) denominator: every per-fn .s, with its unit path (seg/unit fn)
  $FIND "$NM" -name '*.s' \
    | sed -E "s#^$NM/##; s#/([^/]+)\.s\$# \1#" \
    | sort > "$TMP/$region.fns"          # lines: "<seg>/<unit> <fn>"
  total=$(wc -l < "$TMP/$region.fns" | tr -d ' ')

  # 2) all INCLUDE_ASM'd names in this region's src
  $GREP -rhoE 'INCLUDE_ASM\([^,]*,[[:space:]]*[A-Za-z_][A-Za-z_0-9]*\)' "$SRC" 2>/dev/null \
    | sed -E 's/.*,[[:space:]]*([A-Za-z_][A-Za-z_0-9]*)\)/\1/' \
    | sort -u > "$TMP/$region.iasm"

  # 3) guarded (#ifndef TARGET_NATIVE ... INCLUDE_ASM ... #else) names
  $FIND "$SRC" -name '*.c' -exec awk '
    /^[[:space:]]*#ifndef[[:space:]]+TARGET_NATIVE/ { g=1; next }
    /^[[:space:]]*#(else|endif)/                    { g=0; next }
    g && match($0, /INCLUDE_ASM\([^,]*,[[:space:]]*[A-Za-z_][A-Za-z_0-9]*\)/) {
      s = substr($0, RSTART, RLENGTH)
      sub(/.*,[[:space:]]*/, "", s); sub(/\)$/, "", s)
      print s
    }' {} + 2>/dev/null | sort -u > "$TMP/$region.guarded"

  # 4) classify each carved fn
  awk -v iasm="$TMP/$region.iasm" -v guarded="$TMP/$region.guarded" \
      -v src="$SRC" '
    BEGIN {
      while ((getline l < iasm)    > 0) ia[l] = 1
      while ((getline l < guarded) > 0) gu[l] = 1
    }
    {
      unit = $1; fn = $2
      if (gu[fn])          { cov++;  next }
      if (ia[fn])          { wall++; next }
      cfile = src "/" unit ".c"
      if ((getline dummy < cfile) >= 0) { close(cfile); mat++ }
      else                              { only++ }
    }
    END { printf "%d %d %d %d\n", mat+0, cov+0, wall+0, only+0 }
  ' "$TMP/$region.fns" > "$TMP/$region.counts"
  read -r mat cov wall only < "$TMP/$region.counts"

  # 5) whole-ROM context: every glabel splat has ever emitted for the region
  romfns=$($GREP -rh '^glabel ' "$GD/asm/$region" 2>/dev/null | sort -u | wc -l | tr -d ' ')

  pct() { awk -v n="$1" -v d="$2" 'BEGIN { printf "%5.1f%%", d ? 100*n/d : 0 }'; }

  echo "--- region: $region ---"
  printf "  carved functions (per-fn nonmatching .s)  : %5d\n" "$total"
  printf "  matched-by-C   (INCLUDE_ASM removed)      : %5d  (%s of carved)\n" "$mat"  "$(pct "$mat"  "$total")"
  printf "  coverage       (#else TARGET_NATIVE body) : %5d  (%s of carved)\n" "$cov"  "$(pct "$cov"  "$total")"
  printf "  bare walls     (INCLUDE_ASM, no #else)    : %5d  (%s of carved)\n" "$wall" "$(pct "$wall" "$total")"
  printf "  asm-only       (unit has no .c yet)       : %5d  (%s of carved)\n" "$only" "$(pct "$only" "$total")"
  sum=$((mat + cov + wall + only))
  if [ "$sum" -eq "$total" ]; then
    printf "  reconcile: %d + %d + %d + %d = %d == total OK\n" "$mat" "$cov" "$wall" "$only" "$total"
  else
    printf "  reconcile: MISMATCH %d != %d (INVESTIGATE)\n" "$sum" "$total"
  fi
  printf "  whole-ROM context: %s unique glabels disassembled in asm/%s;\n" "$romfns" "$region"
  printf "    the carved denominator above is the per-fn-split slice (%s of them).\n" "$(pct "$total" "$romfns")"
  echo

  tot_all=$((tot_all + total)); mat_all=$((mat_all + mat))
  cov_all=$((cov_all + cov));   wall_all=$((wall_all + wall))
  only_all=$((only_all + only))
done

pct() { awk -v n="$1" -v d="$2" 'BEGIN { printf "%5.1f%%", d ? 100*n/d : 0 }'; }
echo "--- combined (usa + eu) ---"
printf "  carved %d | matched-by-C %d (%s) | coverage %d (%s) | walls %d (%s) | asm-only %d (%s)\n" \
  "$tot_all" \
  "$mat_all"  "$(pct "$mat_all"  "$tot_all")" \
  "$cov_all"  "$(pct "$cov_all"  "$tot_all")" \
  "$wall_all" "$(pct "$wall_all" "$tot_all")" \
  "$only_all" "$(pct "$only_all" "$tot_all")"
echo
echo "(--verify for TRUE byte-exact counts is a documented TODO stub; see -h text in the header.)"
