#!/usr/bin/env python3
# gen_stubs.py - M4 weak stub-table generator (TARGET_NATIVE).
#
# Emits a weak abort-stub for every still-undefined game function so a partial
# native binary LINKS (the function gap from tools/native/linkgap.sh that the
# arena does NOT cover). Each stub is WEAK, so the moment a function gets a real
# #else body (or is decompiled) the strong definition overrides the stub with no
# edit here. A stub is NOT a silent no-op: it calls native_stub_hit() which
# records a sentinel and traps (exit NATIVE_STUB_EXIT) - reaching unimplemented
# code is FLAGGED, not mistaken for a wrong result. See docs/HLE.md M4.
#
# Usage: gen_stubs.py <funcs.txt> <out_stubs.c>
#   funcs.txt = still-undefined function symbols (linkgap residual minus the
#               arena-resolved data globals).
#
# Caveat: a few names in the residual may be data tables, not functions; a
# `void NAME(void)` stub still resolves the link (C has no cross-TU signature
# check), and since stubs trap on call, a never-reached data symbol is harmless.
# When such a symbol is identified, give it real storage (arena / a typed def).

import sys, re

VALID = re.compile(r'^[A-Za-z_]\w*$')


def main():
    if len(sys.argv) != 3:
        sys.exit("usage: gen_stubs.py <funcs.txt> <out_stubs.c>")
    funcs_path, out_path = sys.argv[1:3]
    with open(funcs_path) as f:
        names = sorted({ln.strip() for ln in f if ln.strip() and not ln.startswith('#')})
    names = [n for n in names if VALID.match(n)]

    with open(out_path, "w") as f:
        f.write("/* GENERATED by gen_stubs.py - M4 weak stub table (%d funcs).\n" % len(names))
        f.write(" * Weak abort-stubs for still-undefined game functions so the\n")
        f.write(" * native build links; real definitions override (weak). Hitting\n")
        f.write(" * one traps via native_stub_hit (sentinel + exit), never silent. */\n")
        f.write("#ifdef TARGET_NATIVE\n")
        f.write("#include \"native_stub.h\"\n\n")
        for n in names:
            f.write("__attribute__((weak)) void %s(void) { native_stub_hit(\"%s\"); }\n" % (n, n))
        f.write("\n#endif /* TARGET_NATIVE */\n")

    print("wrote %d weak stubs to %s" % (len(names), out_path))


if __name__ == "__main__":
    main()
