/* GENERATED by gen_arena.py - M2 globals-arena backing block. */
/* One contiguous block mirroring the ROM data-segment layout;  */
/* the generated arena.ld PROVIDEs every global at its ROM-       */
/* relative offset inside this block. A PINE state snapshot loads */
/* via memcpy into __gamedata_start (== &g_dataArena[0]).         */
#ifdef TARGET_NATIVE
__attribute__((aligned(16), section(".gamedata")))
unsigned char g_dataArena[0x14AA90U];
#endif
