#!/usr/bin/env python3
# gen_arena.py - M2 globals-arena generator (production, Mechanic B).
#
# Emits a generated linker-script fragment that places every native data global
# at its ROM-relative offset inside one contiguous .gamedata block, so the
# TARGET_NATIVE link resolves them with ZERO source edits (existing
# `extern T SYM;` decls bind to the PROVIDEd symbols) and exact ROM adjacency.
# See docs/HLE.md (M2) and the prototype A/B comparison that chose Mechanic B
# over macro-deref (no source churn, no per-symbol types - placement only).
#
# Address sourcing (no per-symbol type needed - placement is pure offset):
#   * D_xxxxxx  -> ROM address is the hex in the name (D_1A8A60 -> 0x1A8A60).
#   * named     -> symbol_addrs `SYM = 0x...;`.
#   * alias     -> symbol_addrs comment `... alias SYM ...` on a canonical line
#                  (evidence-based only; documented Ghidra aliases, not guessed).
# Block size = (max placed addr - base) + TAIL_PAD. Per-symbol sizing isn't
# needed: the block is contiguous, symbols are placed by offset, and adjacency
# (indexing past a named global into its neighbour) just lands in the block.
#
# Usage: gen_arena.py <names.txt> <symbol_addrs.txt> <outdir>
#   names.txt = the data-global gap list (linkgap.sh runtime-global bucket).

import sys, os, re

TAIL_PAD = 0x10000  # slack past the highest placed global for its own extent
ALIGN = 16          # ROM data segment is 16-byte aligned


def load_symbol_addrs(path):
    """Return (addr_by_name, addr_by_alias)."""
    addr = {}
    alias = {}
    line_re = re.compile(r'^([A-Za-z_]\w*)\s*=\s*0x([0-9A-Fa-f]+)\s*;(.*)$')
    alias_re = re.compile(r'\balias\s+([A-Za-z_]\w*)')
    with open(path) as f:
        for line in f:
            m = line_re.match(line.strip())
            if not m:
                continue
            name, hexv, comment = m.group(1), m.group(2), m.group(3)
            a = int(hexv, 16)
            addr[name] = a
            for am in alias_re.finditer(comment):
                # first documented alias wins; canonical addr of this line
                alias.setdefault(am.group(1), a)
    return addr, alias


def resolve(name, addr_by_name, addr_by_alias):
    m = re.fullmatch(r'D_([0-9A-Fa-f]{6,8})', name)
    if m:
        return int(m.group(1), 16)
    if name in addr_by_name:
        return addr_by_name[name]
    if name in addr_by_alias:
        return addr_by_alias[name]
    return None


def main():
    if len(sys.argv) != 4:
        sys.exit("usage: gen_arena.py <names.txt> <symbol_addrs.txt> <outdir>")
    names_path, syms_path, outdir = sys.argv[1:4]
    os.makedirs(outdir, exist_ok=True)

    with open(names_path) as f:
        names = sorted({ln.strip() for ln in f if ln.strip()})
    addr_by_name, addr_by_alias = load_symbol_addrs(syms_path)

    placed = []      # (name, addr)
    unresolved = []
    for n in names:
        a = resolve(n, addr_by_name, addr_by_alias)
        if a is None:
            unresolved.append(n)
        else:
            placed.append((n, a))
    placed.sort(key=lambda t: t[1])

    base = placed[0][1]
    span = (placed[-1][1] - base) + TAIL_PAD

    # ---- arena_storage.c : the contiguous backing block (the .gamedata bytes)
    with open(os.path.join(outdir, "arena_storage.c"), "w") as f:
        f.write("/* GENERATED by gen_arena.py - M2 globals-arena backing block. */\n")
        f.write("/* One contiguous block mirroring the ROM data-segment layout;  */\n")
        f.write("/* the generated arena.ld PROVIDEs every global at its ROM-       */\n")
        f.write("/* relative offset inside this block. A PINE state snapshot loads */\n")
        f.write("/* via memcpy into __gamedata_start (== &g_dataArena[0]).         */\n")
        f.write("#ifdef TARGET_NATIVE\n")
        f.write("__attribute__((aligned(%d), section(\".gamedata\")))\n" % ALIGN)
        f.write("unsigned char g_dataArena[0x%XU];\n" % span)
        f.write("#endif\n")

    # ---- arena.ld : place .gamedata after .bss, PROVIDE each symbol by offset
    with open(os.path.join(outdir, "arena.ld"), "w") as f:
        f.write("/* GENERATED by gen_arena.py - M2 globals arena (Mechanic B).\n")
        f.write(" * ROM base 0x%06X, span 0x%X (%d placed, %d unresolved).\n"
                % (base, span, len(placed), len(unresolved)))
        f.write(" * INSERT fragment: augments the default link script. */\n")
        f.write("SECTIONS {\n")
        f.write("  .gamedata (NOLOAD) : ALIGN(%d) {\n" % ALIGN)
        f.write("    __gamedata_start = .;\n")
        f.write("    *(.gamedata)\n")
        f.write("    . = __gamedata_start + 0x%X;\n" % span)
        f.write("    __gamedata_end = .;\n")
        f.write("  }\n")
        f.write("}\n")
        f.write("INSERT AFTER .bss;\n\n")
        f.write("/* ROM base = 0x%06X */\n" % base)
        for name, a in placed:
            f.write("PROVIDE(%s = __gamedata_start + 0x%X);\n" % (name, a - base))

    # ---- arena_map.txt : machine-readable placement map for the PINE snapshot
    # seeder (tester's state-seeding harness). Seeding only needs base/span (the
    # whole [base, base+span) ROM range copies into &g_dataArena[0]); the
    # per-symbol rows let the harness validate a named global's value against the
    # snapshot byte at its rom_addr.
    with open(os.path.join(outdir, "arena_map.txt"), "w") as f:
        f.write("# native globals-arena placement map (Mechanic B).\n")
        f.write("# storage symbol: g_dataArena  ==  __gamedata_start (linker)\n")
        f.write("# seed: memcpy snapshot[rom_addr] -> g_dataArena[rom_addr - base]\n")
        f.write("#       for rom_addr in [base, base+span).\n")
        f.write("# base 0x%06X  span 0x%X  placed %d\n" % (base, span, len(placed)))
        f.write("# columns: <symbol> <rom_addr> <arena_offset>\n")
        for name, a in placed:
            f.write("%s 0x%06X 0x%X\n" % (name, a, a - base))

    # ---- arena_unresolved.txt : the tail needing canonical addresses (Track-B)
    with open(os.path.join(outdir, "arena_unresolved.txt"), "w") as f:
        f.write("# Native data globals referenced by #else bodies that have NO\n")
        f.write("# canonical address (not a D_xxxxxx name, not in symbol_addrs,\n")
        f.write("# not a documented alias). Each needs its ROM address recovered\n")
        f.write("# in Ghidra and added to symbol_addrs (Track-B) before the arena\n")
        f.write("# can place it. Count: %d\n" % len(unresolved))
        for n in unresolved:
            f.write(n + "\n")

    print("base=0x%06X span=0x%X (%d bytes)" % (base, span, span))
    print("placed=%d  unresolved=%d  (of %d)" % (len(placed), len(unresolved), len(names)))
    print("wrote arena.ld, arena_storage.c, arena_map.txt, arena_unresolved.txt to", outdir)


if __name__ == "__main__":
    main()
