.include "macro.inc"

.section .bss, "wa"

/* Generated by spimdisasm 1.41.0 */

nonmatching D_0013C080, 0x80

dlabel D_0013C080
    /* 0013C080 */ .space 0x80

nonmatching D_0013C100, 0x80

dlabel D_0013C100
    /* 0013C100 */ .space 0x80

nonmatching D_0013C180, 0x80

dlabel D_0013C180
    /* 0013C180 */ .space 0x80

nonmatching D_0013C200, 0x400

dlabel D_0013C200
    /* 0013C200 */ .space 0x400

nonmatching D_0013C600, 0x8

dlabel D_0013C600
    /* 0013C600 */ .space 0x08

nonmatching D_0013C608, 0x408

dlabel D_0013C608
    /* 0013C608 */ .space 0x408

nonmatching D_0013CA10, 0x30

dlabel D_0013CA10
    /* 0013CA10 */ .space 0x30

nonmatching D_0013CA40, 0x110

dlabel D_0013CA40
    /* 0013CA40 */ .space 0x110

nonmatching D_0013CB50, 0x30

dlabel D_0013CB50
    /* 0013CB50 */ .space 0x30

nonmatching D_0013CB80, 0x140

dlabel D_0013CB80
    /* 0013CB80 */ .space 0x140

nonmatching D_0013CCC0, 0x140

dlabel D_0013CCC0
    /* 0013CCC0 */ .space 0x140

nonmatching D_0013CE00, 0x80

dlabel D_0013CE00
    /* 0013CE00 */ .space 0x80

nonmatching D_0013CE80, 0x80

dlabel D_0013CE80
    /* 0013CE80 */ .space 0x80

nonmatching D_0013CF00, 0x40

dlabel D_0013CF00
    /* 0013CF00 */ .space 0x40

nonmatching D_0013CF40, 0x14

dlabel D_0013CF40
    /* 0013CF40 */ .space 0x14

nonmatching D_0013CF54, 0x4

dlabel D_0013CF54
    /* 0013CF54 */ .space 0x04

nonmatching D_0013CF58, 0x8

dlabel D_0013CF58
    /* 0013CF58 */ .space 0x08

nonmatching D_0013CF60, 0x4

dlabel D_0013CF60
    /* 0013CF60 */ .space 0x04

nonmatching D_0013CF64, 0x8

dlabel D_0013CF64
    /* 0013CF64 */ .space 0x08

nonmatching D_0013CF6C, 0x14

dlabel D_0013CF6C
    /* 0013CF6C */ .space 0x14

nonmatching D_0013CF80, 0x100

dlabel D_0013CF80
    /* 0013CF80 */ .space 0x100

nonmatching D_0013D080, 0x80

dlabel D_0013D080
    /* 0013D080 */ .space 0x80

nonmatching D_0013D100, 0x800

dlabel D_0013D100
    /* 0013D100 */ .space 0x800

nonmatching D_0013D900, 0x800

dlabel D_0013D900
    /* 0013D900 */ .space 0x800

nonmatching D_0013E100, 0x800

dlabel D_0013E100
    /* 0013E100 */ .space 0x800

nonmatching D_0013E900, 0x40

dlabel D_0013E900
    /* 0013E900 */ .space 0x40

nonmatching D_0013E940, 0x40

dlabel D_0013E940
    /* 0013E940 */ .space 0x40

nonmatching D_0013E980, 0xC40

dlabel D_0013E980
    /* 0013E980 */ .space 0xC40

nonmatching D_0013F5C0, 0x40

dlabel D_0013F5C0
    /* 0013F5C0 */ .space 0x40

nonmatching D_0013F600, 0x880

dlabel D_0013F600
    /* 0013F600 */ .space 0x880

nonmatching D_0013FE80, 0x200

dlabel D_0013FE80
    /* 0013FE80 */ .space 0x200

nonmatching D_00140080, 0x28

dlabel D_00140080
    /* 00140080 */ .space 0x28

nonmatching D_001400A8, 0x18

dlabel D_001400A8
    /* 001400A8 */ .space 0x18

nonmatching D_001400C0, 0x40

dlabel D_001400C0
    /* 001400C0 */ .space 0x40

nonmatching D_00140100, 0x40

dlabel D_00140100
    /* 00140100 */ .space 0x40

nonmatching D_00140140, 0x40

dlabel D_00140140
    /* 00140140 */ .space 0x40

nonmatching D_00140180, 0x40

dlabel D_00140180
    /* 00140180 */ .space 0x40

nonmatching D_001401C0, 0x140

dlabel D_001401C0
    /* 001401C0 */ .space 0x140

nonmatching D_00140300, 0x200

dlabel D_00140300
    /* 00140300 */ .space 0x200

nonmatching D_00140500, 0x28

dlabel D_00140500
    /* 00140500 */ .space 0x28

nonmatching D_00140528, 0x18

dlabel D_00140528
    /* 00140528 */ .space 0x18

nonmatching D_00140540, 0x1080

dlabel D_00140540
    /* 00140540 */ .space 0x1080

nonmatching D_001415C0, 0x200

dlabel D_001415C0
    /* 001415C0 */ .space 0x200

nonmatching D_001417C0, 0x8

dlabel D_001417C0
    /* 001417C0 */ .space 0x08

nonmatching D_001417C8, 0x8

dlabel D_001417C8
    /* 001417C8 */ .space 0x08

nonmatching D_001417D0, 0x8

dlabel D_001417D0
    /* 001417D0 */ .space 0x08

nonmatching D_001417D8, 0x8

dlabel D_001417D8
    /* 001417D8 */ .space 0x08

nonmatching D_001417E0, 0x8

dlabel D_001417E0
    /* 001417E0 */ .space 0x08

nonmatching D_001417E8, 0x4

dlabel D_001417E8
    /* 001417E8 */ .space 0x04

nonmatching D_001417EC, 0x4

dlabel D_001417EC
    /* 001417EC */ .space 0x04

nonmatching D_001417F0, 0x10

dlabel D_001417F0
    /* 001417F0 */ .space 0x10

nonmatching D_00141800, 0x8

dlabel D_00141800
    /* 00141800 */ .space 0x08

nonmatching D_00141808, 0x8

dlabel D_00141808
    /* 00141808 */ .space 0x08

nonmatching D_00141810, 0x28

dlabel D_00141810
    /* 00141810 */ .space 0x28

nonmatching D_00141838, 0x8

dlabel D_00141838
    /* 00141838 */ .space 0x08

nonmatching D_00141840, 0x4

dlabel D_00141840
    /* 00141840 */ .space 0x04

nonmatching D_00141844, 0x4

dlabel D_00141844
    /* 00141844 */ .space 0x04

nonmatching D_00141848, 0x8

dlabel D_00141848
    /* 00141848 */ .space 0x08

nonmatching D_00141850, 0x8

dlabel D_00141850
    /* 00141850 */ .space 0x08

nonmatching D_00141858, 0x210

dlabel D_00141858
    /* 00141858 */ .space 0x210

nonmatching D_00141A68, 0x28

dlabel D_00141A68
    /* 00141A68 */ .space 0x28

nonmatching D_00141A90, 0x30

dlabel D_00141A90
    /* 00141A90 */ .space 0x30

nonmatching D_00141AC0, 0x10

dlabel D_00141AC0
    /* 00141AC0 */ .space 0x10

nonmatching D_00141AD0, 0x8

dlabel D_00141AD0
    /* 00141AD0 */ .space 0x08

nonmatching D_00141AD8, 0x28

dlabel D_00141AD8
    /* 00141AD8 */ .space 0x28

nonmatching g_mcRpcClient, 0x24

dlabel g_mcRpcClient
    /* 00141B00 */ .space 0x24

nonmatching g_mcInitialized, 0x4

dlabel g_mcInitialized
    /* 00141B24 */ .space 0x04

nonmatching D_00141B28, 0x4

dlabel D_00141B28
    /* 00141B28 */ .space 0x04

nonmatching D_00141B2C, 0x4

dlabel D_00141B2C
    /* 00141B2C */ .space 0x04

nonmatching D_00141B30, 0x50

dlabel D_00141B30
    /* 00141B30 */ .space 0x50

nonmatching D_00141B80, 0x30

dlabel D_00141B80
    /* 00141B80 */ .space 0x30

nonmatching D_00141BB0, 0x14

dlabel D_00141BB0
    /* 00141BB0 */ .space 0x14

nonmatching D_00141BC4, 0x43C

dlabel D_00141BC4
    /* 00141BC4 */ .space 0x43C

nonmatching D_00142000, 0x10C0

dlabel D_00142000
    /* 00142000 */ .space 0x10C0

nonmatching g_mcRpcResult, 0x48

dlabel g_mcRpcResult
    /* 001430C0 */ .space 0x48

nonmatching D_00143108, 0x28

dlabel D_00143108
    /* 00143108 */ .space 0x28

nonmatching D_00143130, 0x50

dlabel D_00143130
    /* 00143130 */ .space 0x50

nonmatching D_00143180, 0x400

dlabel D_00143180
    /* 00143180 */ .space 0x400

nonmatching D_00143580, 0x80

dlabel D_00143580
    /* 00143580 */ .space 0x80

nonmatching D_00143600, 0x40

dlabel D_00143600
    /* 00143600 */ .space 0x40

nonmatching D_00143640, 0x10

dlabel D_00143640
    /* 00143640 */ .space 0x10

nonmatching D_00143650, 0x32F0

dlabel D_00143650
    /* 00143650 */ .space 0x32F0

nonmatching D_00146940, 0x200

dlabel D_00146940
    /* 00146940 */ .space 0x200

nonmatching D_00146B40, 0x180

dlabel D_00146B40
    /* 00146B40 */ .space 0x180

nonmatching D_00146CC0, 0x1000

dlabel D_00146CC0
    /* 00146CC0 */ .space 0x1000

nonmatching D_00147CC0, 0x1000

dlabel D_00147CC0
    /* 00147CC0 */ .space 0x1000

nonmatching D_00148CC0, 0x1000

dlabel D_00148CC0
    /* 00148CC0 */ .space 0x1000

nonmatching D_00149CC0, 0x1000

dlabel D_00149CC0
    /* 00149CC0 */ .space 0x1000

nonmatching D_0014ACC0, 0x440

dlabel D_0014ACC0
    /* 0014ACC0 */ .space 0x440

nonmatching D_0014B100, 0x440

dlabel D_0014B100
    /* 0014B100 */ .space 0x440

nonmatching g_discToc, 0x32C

dlabel g_discToc
    /* 0014B540 */ .space 0x32C

nonmatching g_levelWadBaseLbn, 0x40

dlabel g_levelWadBaseLbn
    /* 0014B86C */ .space 0x40

nonmatching g_globalWadBaseLbn, 0xA64

dlabel g_globalWadBaseLbn
    /* 0014B8AC */ .space 0xA64

nonmatching g_menuBgImageTocA, 0x28

dlabel g_menuBgImageTocA
    /* 0014C310 */ .space 0x28

nonmatching g_menuBgImageTocB, 0x8B8

dlabel g_menuBgImageTocB
    /* 0014C338 */ .space 0x8B8

nonmatching g_textTableLbnOffset, 0x2774

dlabel g_textTableLbnOffset
    /* 0014CBF0 */ .space 0x2774

nonmatching g_sceneWadBaseLbn, 0x4

dlabel g_sceneWadBaseLbn
    /* 0014F364 */ .space 0x04

nonmatching g_globalSceneToc, 0x30

dlabel g_globalSceneToc
    /* 0014F368 */ .space 0x30

nonmatching g_loadingSceneWadToc, 0xA80

dlabel g_loadingSceneWadToc
    /* 0014F398 */ .space 0xA80

nonmatching g_shipModelToc, 0x18

dlabel g_shipModelToc
    /* 0014FE18 */ .space 0x18

nonmatching g_shipTextureToc, 0x614

dlabel g_shipTextureToc
    /* 0014FE30 */ .space 0x614

nonmatching g_castModelWadBaseLbn, 0x4

dlabel g_castModelWadBaseLbn
    /* 00150444 */ .space 0x04

nonmatching g_castModelToc, 0xF0

dlabel g_castModelToc
    /* 00150448 */ .space 0xF0

nonmatching g_levelTocDirectory, 0x2A0

dlabel g_levelTocDirectory
    /* 00150538 */ .space 0x2A0

nonmatching g_levelTocHeader, 0x60

dlabel g_levelTocHeader
    /* 001507D8 */ .space 0x60

nonmatching g_levelAssetToc, 0x1018

dlabel g_levelAssetToc
    /* 00150838 */ .space 0x1018

nonmatching g_levelDialogToc, 0x13C8

dlabel g_levelDialogToc
    /* 00151850 */ .space 0x13C8

nonmatching g_loadedShipModelVariant, 0x8

dlabel g_loadedShipModelVariant
    /* 00152C18 */ .space 0x08

nonmatching g_exitSceneMode, 0xC

dlabel g_exitSceneMode
    /* 00152C20 */ .space 0x0C

nonmatching g_scenePlayerFadedOut, 0x2

dlabel g_scenePlayerFadedOut
    /* 00152C2C */ .space 0x02

nonmatching g_loadingSceneVariant, 0x2

dlabel g_loadingSceneVariant
    /* 00152C2E */ .space 0x02

nonmatching g_loadedShipTextureIndex, 0x8

dlabel g_loadedShipTextureIndex
    /* 00152C30 */ .space 0x08

nonmatching g_shipTexDescriptor, 0x8

dlabel g_shipTexDescriptor
    /* 00152C38 */ .space 0x08

nonmatching g_shipTakeoffSplineIndex, 0x24

dlabel g_shipTakeoffSplineIndex
    /* 00152C40 */ .space 0x24

nonmatching g_loadingSceneIndex, 0x4

dlabel g_loadingSceneIndex
    /* 00152C64 */ .space 0x04

nonmatching g_loadingScenesPlayed, 0x2D398

dlabel g_loadingScenesPlayed
    /* 00152C68 */ .space 0x2D398

nonmatching D_00180000, 0x8510

dlabel D_00180000
    /* 00180000 */ .space 0x8510

nonmatching g_bestiaryKillCounts, 0x150

dlabel g_bestiaryKillCounts
    /* 00188510 */ .space 0x150

nonmatching g_listenerPosHistory, 0x40

dlabel g_listenerPosHistory
    /* 00188660 */ .space 0x40

nonmatching g_listenerPosHistoryIdx, 0x8

dlabel g_listenerPosHistoryIdx
    /* 001886A0 */ .space 0x08

nonmatching g_sndChannelVolumes, 0x28

dlabel g_sndChannelVolumes
    /* 001886A8 */ .space 0x28

nonmatching g_soundEmitterTable, 0x16D0

dlabel g_soundEmitterTable
    /* 001886D0 */ .space 0x16D0

nonmatching g_listenerOcclusionProbes, 0x60

dlabel g_listenerOcclusionProbes
    /* 00189DA0 */ .space 0x60

nonmatching g_soundBankHandles, 0xA0

dlabel g_soundBankHandles
    /* 00189E00 */ .space 0xA0

nonmatching g_heroPos, 0x15C

dlabel g_heroPos
    /* 00189EA0 */ .space 0x15C

nonmatching g_nNanotechBonusHealTimer, 0x1698

dlabel g_nNanotechBonusHealTimer
    /* 00189FFC */ .space 0x1698

nonmatching g_giantClankHealth, 0xA1C

dlabel g_giantClankHealth
    /* 0018B694 */ .space 0xA1C

nonmatching g_pHeroMoby, 0x24

dlabel g_pHeroMoby
    /* 0018C0B0 */ .space 0x24

nonmatching g_bPlayerMode, 0x20C

dlabel g_bPlayerMode
    /* 0018C0D4 */ .space 0x20C

nonmatching g_air, 0xC

dlabel g_air
    /* 0018C2E0 */ .space 0x0C

nonmatching g_health, 0xEF8C

dlabel g_health
    /* 0018C2EC */ .space 0xEF8C

nonmatching g_platinumBoltFlags, 0x7930

dlabel g_platinumBoltFlags
    /* 0019B278 */ .space 0x7930

nonmatching g_saveImageGlobal, 0x2800

dlabel g_saveImageGlobal
    /* 001A2BA8 */ .space 0x2800

nonmatching g_saveImageArea, 0x1004

dlabel g_saveImageArea
    /* 001A53A8 */ .space 0x1004

nonmatching g_fileLoadState, 0x2

dlabel g_fileLoadState
    /* 001A63AC */ .space 0x02

nonmatching g_bFileLoadAborted, 0x2

dlabel g_bFileLoadAborted
    /* 001A63AE */ .space 0x02

nonmatching g_fileLoadLbn, 0x8

dlabel g_fileLoadLbn
    /* 001A63B0 */ .space 0x08

nonmatching g_fileLoadSectorCount, 0x4

dlabel g_fileLoadSectorCount
    /* 001A63B8 */ .space 0x04

nonmatching g_fileLoadDest, 0x4

dlabel g_fileLoadDest
    /* 001A63BC */ .space 0x04

nonmatching g_fileLoadCallback, 0x4

dlabel g_fileLoadCallback
    /* 001A63C0 */ .space 0x04

nonmatching g_fileLoadCallbackArg, 0x8

dlabel g_fileLoadCallbackArg
    /* 001A63C4 */ .space 0x08

nonmatching g_pendingDialogVoiceId, 0x1C

dlabel g_pendingDialogVoiceId
    /* 001A63CC */ .space 0x1C

nonmatching g_cdReadMode, 0x28

dlabel g_cdReadMode
    /* 001A63E8 */ .space 0x28

nonmatching g_dialogVoiceActive, 0x4

dlabel g_dialogVoiceActive
    /* 001A6410 */ .space 0x04

nonmatching g_dialogVoiceId, 0x6

dlabel g_dialogVoiceId
    /* 001A6414 */ .space 0x06

nonmatching g_dialogVoicePhase, 0x66

dlabel g_dialogVoicePhase
    /* 001A641A */ .space 0x66

nonmatching g_gsScreenContext, 0x180

dlabel g_gsScreenContext
    /* 001A6480 */ .space 0x180

nonmatching g_screenBlitPacketA, 0x260

dlabel g_screenBlitPacketA
    /* 001A6600 */ .space 0x260

nonmatching g_screenBlitPacketB, 0x4E0

dlabel g_screenBlitPacketB
    /* 001A6860 */ .space 0x4E0

nonmatching g_screenClearPacketA, 0x150

dlabel g_screenClearPacketA
    /* 001A6D40 */ .space 0x150

nonmatching g_screenClearPacketB, 0x170

dlabel g_screenClearPacketB
    /* 001A6E90 */ .space 0x170

nonmatching D_001A7000, 0xC

dlabel D_001A7000
    /* 001A7000 */ .space 0x0C

nonmatching D_001A700C, 0x34

dlabel D_001A700C
    /* 001A700C */ .space 0x34

nonmatching D_001A7040, 0x24

dlabel D_001A7040
    /* 001A7040 */ .space 0x24

nonmatching D_001A7064, 0x1C

dlabel D_001A7064
    /* 001A7064 */ .space 0x1C

nonmatching D_001A7080, 0x4

dlabel D_001A7080
    /* 001A7080 */ .space 0x04

nonmatching D_001A7084, 0x3C

dlabel D_001A7084
    /* 001A7084 */ .space 0x3C

nonmatching D_001A70C0, 0x40

dlabel D_001A70C0
    /* 001A70C0 */ .space 0x40

nonmatching D_001A7100, 0x10

dlabel D_001A7100
    /* 001A7100 */ .space 0x10

nonmatching g_sndIopLoadStatus, 0x2F

dlabel g_sndIopLoadStatus
    /* 001A7110 */ .space 0x2F

nonmatching D_001A713F, 0x1

dlabel D_001A713F
    /* 001A713F */ .space 0x01

nonmatching D_001A7140, 0x24

dlabel D_001A7140
    /* 001A7140 */ .space 0x24

nonmatching D_001A7164, 0x1C

dlabel D_001A7164
    /* 001A7164 */ .space 0x1C

nonmatching D_001A7180, 0x40

dlabel D_001A7180
    /* 001A7180 */ .space 0x40

nonmatching D_001A71C0, 0x4

dlabel D_001A71C0
    /* 001A71C0 */ .space 0x04

nonmatching D_001A71C4, 0x3C

dlabel D_001A71C4
    /* 001A71C4 */ .space 0x3C

nonmatching g_hblankTicksAccum, 0x8

dlabel g_hblankTicksAccum
    /* 001A7200 */ .space 0x08

nonmatching g_vblankCount, 0x8

dlabel g_vblankCount
    /* 001A7208 */ .space 0x08

nonmatching D_001A7210, 0x70

dlabel D_001A7210
    /* 001A7210 */ .space 0x70

nonmatching g_levelStagingState, 0x4

dlabel g_levelStagingState
    /* 001A7280 */ .space 0x04

nonmatching g_bLoadingSceneBanksHeld, 0x4

dlabel g_bLoadingSceneBanksHeld
    /* 001A7284 */ .space 0x04

nonmatching g_pLoadedSegment, 0x4

dlabel g_pLoadedSegment
    /* 001A7288 */ .space 0x04

nonmatching g_pStagedChunkB, 0x4

dlabel g_pStagedChunkB
    /* 001A728C */ .space 0x04

nonmatching g_loadedArmorVariant, 0x4

dlabel g_loadedArmorVariant
    /* 001A7290 */ .space 0x04

nonmatching g_pPlayerModelBuffer, 0x4

dlabel g_pPlayerModelBuffer
    /* 001A7294 */ .space 0x04

nonmatching g_playerTexCount, 0x8

dlabel g_playerTexCount
    /* 001A7298 */ .space 0x08

nonmatching g_playerTexDescriptors, 0x20

dlabel g_playerTexDescriptors
    /* 001A72A0 */ .space 0x20

nonmatching g_loadedHeldItemModelId, 0x8

dlabel g_loadedHeldItemModelId
    /* 001A72C0 */ .space 0x08

nonmatching g_heldItemTexDescriptor, 0x8

dlabel g_heldItemTexDescriptor
    /* 001A72C8 */ .space 0x08

nonmatching g_vramAllocCursor, 0x4

dlabel g_vramAllocCursor
    /* 001A72D0 */ .space 0x04

nonmatching g_vramDynamicBase, 0x4

dlabel g_vramDynamicBase
    /* 001A72D4 */ .space 0x04

nonmatching g_vramFrameBufA, 0x4

dlabel g_vramFrameBufA
    /* 001A72D8 */ .space 0x04

nonmatching g_vramFrameBufB, 0x4

dlabel g_vramFrameBufB
    /* 001A72DC */ .space 0x04

nonmatching g_vramZBuffer, 0x4

dlabel g_vramZBuffer
    /* 001A72E0 */ .space 0x04

nonmatching g_vramTextureBase, 0x5C

dlabel g_vramTextureBase
    /* 001A72E4 */ .space 0x5C

nonmatching g_screenWidth, 0x4

dlabel g_screenWidth
    /* 001A7340 */ .space 0x04

nonmatching g_screenHeight, 0xC

dlabel g_screenHeight
    /* 001A7344 */ .space 0x0C

nonmatching g_gsPixelOffsetX, 0x4

dlabel g_gsPixelOffsetX
    /* 001A7350 */ .space 0x04

nonmatching g_gsPixelOffsetY, 0xCC

dlabel g_gsPixelOffsetY
    /* 001A7354 */ .space 0xCC

nonmatching g_nSaveLoadStatusCode, 0xC

dlabel g_nSaveLoadStatusCode
    /* 001A7420 */ .space 0x0C

nonmatching g_gsScreenContextPtr, 0x4

dlabel g_gsScreenContextPtr
    /* 001A742C */ .space 0x04

nonmatching g_rawReadStallTimer, 0x4

dlabel g_rawReadStallTimer
    /* 001A7430 */ .space 0x04

nonmatching g_bRawReadFellBack, 0x3C

dlabel g_bRawReadFellBack
    /* 001A7434 */ .space 0x3C

nonmatching D_001A7470, 0x10

dlabel D_001A7470
    /* 001A7470 */ .space 0x10
